using Terrajobst.ApiFingerprint.Tests.Infra;

namespace Terrajobst.ApiFingerprint.Tests;

public class ApiFingerprintTests
{
    [Theory]
    [MemberData(nameof(GetProviders))]
    public void Test1(FingerprintProvider provider)
    {
        var source =
            """
            namespace N;

            public class C
            {
                public void M(int x) { }
            }
            """;

        Check(provider, source, [
            "T:N.C",
            "M:N.C.#ctor",
            "M:N.C.M(System.Int32)"
        ]);
    }

    public static IEnumerable<object[]> GetProviders()
    {
        return FingerprintProvider.All.Select(p => new object[] { p });
    }
    
    private static void Check(FingerprintProvider provider, string source, string[] expectedDocIds)
    {
        var assembly = Compiler.Compile(source);
        var expectedFingerprints = expectedDocIds.Select(d => new FingerprintResult(d)).Order().ToArray();
       
        var actualFingerprints = provider.GetFingerprintsExcludingAutoGenerated(assembly);
        Array.Sort(actualFingerprints);
        Assert.Equal(expectedFingerprints, actualFingerprints);
    }
}

